kind: Pod
apiVersion: v1
metadata:
  name: wasmedge-test
spec:
  restartPolicy: Never
  runtimeClassName: wasm
  containers:
  - name: wasmedge-test
    image: wasmedge/example-wasi:latest
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
